
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

vb:
  cmd:
    createvm: VBoxManage createvm --name _vmName_ --ostype _osType_ --register